#!/bin/bash

# Name of the virtual environment
ENV_NAME="env"

# Create virtual environment
python3 -m venv $ENV_NAME

# Activate the virtual environment
source $ENV_NAME/bin/activate

# Install requirements
pip install -r requirements.txt

echo "Setup completed. Virtual Environment '$ENV_NAME' is ready and activated."