---
title: "LR_Bayesian"
author: ""
date: "2024-04-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(corrplot)
library(scales)
library(stats)
library(rstan)
library(caret)
library(ggplot2)
```

### Load the dataset
```{r read, echo=FALSE}
df <- read.csv("/Users/jasper/Desktop/Stats451 Final Project/heart.csv")
```

### Understand basic info of the dataset

```{r}
table(df$smoking)
df$DEATH_EVENT %>% table()
na_counts <- sum(is.na(df))
na_counts
summary(df)
```

### Fitting Logistic Regression Model

```{r}
set.seed(451)
y <- df$DEATH_EVENT
X <- df %>% select(-DEATH_EVENT, -time) %>% as.data.frame()
X <- X %>% data.matrix()

model <- glm(y ~ X, family = binomial(link = "logit"))
summary(model)
```

### Bayesian Logistic Regression using Stan

```{r}
stan_model_code <- "
data {
  int<lower=0> N;                   
  int<lower=0, upper=1> y[N];       
  vector[N] age;                      
  vector[N] anaemia;                
  vector[N] creatinine_phosphokinase;
  vector[N] diabetes;                 
  vector[N] ejection_fraction;        
  vector[N] high_blood_pressure;      
  vector[N] platelets;                
  vector[N] serum_creatinine;         
  vector[N] serum_sodium;           
  vector[N] sex;                      
  vector[N] smoking;                  
}
parameters {
  real alpha;                       
  real beta_age;
  real beta_anaemia;
  real beta_cpk;              
  real beta_diabetes;
  real beta_ef;                      
  real beta_hbp;                     
  real beta_platelets;
  real beta_s_creatinine;           
  real beta_s_sodium;                 
  real beta_sex;
  real beta_smoking;
}
model {
  // Priors
  alpha ~ normal(0, 10);
  beta_age ~ normal(0, 10);
  beta_anaemia ~ normal(0, 10);
  beta_cpk ~ normal(0, 10);
  beta_diabetes ~ normal(0, 10);
  beta_ef ~ normal(0, 10);
  beta_hbp ~ normal(0, 10);
  beta_platelets ~ normal(0, 10);
  beta_s_creatinine ~ normal(0, 10);
  beta_s_sodium ~ normal(0, 10);
  beta_sex ~ normal(0, 10);
  beta_smoking ~ normal(0, 10);
  
  // Likelihood
  for (i in 1:N)
    y[i] ~ bernoulli_logit(alpha + beta_age * age[i] + beta_anaemia * anaemia[i] + beta_cpk * creatinine_phosphokinase[i] +
                           beta_diabetes * diabetes[i] + beta_ef * ejection_fraction[i] + beta_hbp * high_blood_pressure[i] +
                           beta_platelets * platelets[i] + beta_s_creatinine * serum_creatinine[i] + beta_s_sodium * serum_sodium[i] +
                           beta_sex * sex[i] + beta_smoking * smoking[i]);
}
"
data_for_stan <- list(
  N = length(y),
  y = as.integer(y),
  age = as.numeric(df$age),
  anaemia = as.numeric(df$anaemia),
  creatinine_phosphokinase = as.numeric(df$creatinine_phosphokinase),
  diabetes = as.numeric(df$diabetes),
  ejection_fraction = as.numeric(df$ejection_fraction),
  high_blood_pressure = as.numeric(df$high_blood_pressure),
  platelets = as.numeric(df$platelets),
  serum_creatinine = as.numeric(df$serum_creatinine),
  serum_sodium = as.numeric(df$serum_sodium),
  sex = as.numeric(df$sex),
  smoking = as.numeric(df$smoking)
)

fit <- stan(model_code = stan_model_code, data = data_for_stan, iter = 10000, chains = 4, warmup = 1000, seed = 101)
print(fit)
```

### Traceplot

```{r}
traceplot(fit)
```

### Credible Interval

```{r}
samples <- extract(fit)
continuous_params <- c("alpha", "beta_age", "beta_cpk", "beta_ef", "beta_platelets", 
                        "beta_s_creatinine", "beta_s_sodium")

for (param in continuous_params) {
  param_samples <- samples[[param]]
  ci <- quantile(param_samples, probs = c(0.025, 0.975))
  cat("95% CI for", param, ":", ci, "\n")

  df <- data.frame(value = param_samples)
  p <- ggplot(df, aes(x = value)) +
    geom_histogram(bins = 30, fill = "lightblue", color = "black") +
    ggtitle(paste("Histogram of posterior", param)) +
    xlab(param) +
    ylab("Frequency") +
    theme_minimal()

  print(p)
}
```

```{r}
categorical_params <- c("beta_anaemia", "beta_diabetes", "beta_hbp",
                       "beta_sex", "beta_smoking")

for (param in categorical_params) {
  param_samples <- samples[[param]]
  ci <- quantile(param_samples, probs = c(0.025, 0.975))
  cat("95% CI for", param, ":", ci, "\n")
  
  df <- data.frame(value = param_samples)
  p <- ggplot(df, aes(x = value)) +
    geom_histogram(bins = 100, fill = "lightblue", color = "black") +
    ggtitle(paste("Histogram of", param)) +
    xlab(param) +
    ylab("Frequency") +
    theme_minimal()

  print(p)
}
```


### EDA

**Time Distribution for each DEATH_EVENT**

```{r}
y0 <- df[df$DEATH_EVENT == 0,]
y1 <- df[df$DEATH_EVENT == 1,]

hist(y0$time, main="Time Distribution for DEATH_EVENT = 0", xlab="Time", col="lightblue")
hist(y1$time, main="Time Distribution for DEATH_EVENT = 1", xlab="Time", col="lightgreen")
```

**Factor all categorical variables**

```{r, echo = FALSE, include = FALSE}
df$anaemia <- factor(df$anaemia, levels = c(0, 1), 
                        labels = c("No anemia", "Anemia"))
df$diabetes <- factor(df$diabetes, levels = c(0, 1),
                      labels = c("No diabetes", "Diabetes"))
df$high_blood_pressure <- factor(df$high_blood_pressure, levels = c(0, 1),
                                 labels = c("No hbp", "Hbp"))
df$sex <- factor(df$sex, levels = c(0, 1),
                 labels = c("Female", "Male"))
df$smoking <- factor(df$smoking, levels = c(0, 1),
                     labels = c("No smoking", "Smoking"))
df$DEATH_EVENT <- factor(df$DEATH_EVENT, levels = c(0, 1),
                         labels = c("Alive", "Dead"))
```

**Numerical Variable EDA**

```{r}
deadYes <- subset(df, DEATH_EVENT == 'Dead')

numerical_Yes=deadYes[ ,c('age','creatinine_phosphokinase','ejection_fraction', 'platelets', 'serum_creatinine', 'serum_sodium')]
Yes_matrix <- cor(numerical_Yes, use = "complete.obs")
Yes_matrix <- round(Yes_matrix, 3)

par(cex.main=0.8)
lhei = c(2, 5)
heatmap.2(Yes_matrix, dendrogram = 'none',
          Rowv=NULL, Colv=NULL,
          trace='none', symm=TRUE,
          cexRow = 0.75, cexCol=0.75,
          key = FALSE, srtCol = 30,
          adjCol = c(0.5, 0.5),
          srtRow=50, adjRow=c(0.5,0.5),
          offsetRow = -43,
          col = colorRampPalette(c("blue", "white", "orange"))(200),
          margins = c(6.5, 5), lhei= lhei,
          cellnote = Yes_matrix, notecol = "black",
          )
```

```{r}
deadNo <- subset(df, DEATH_EVENT == 'Alive')

numerical_No=deadNo[ ,c('age','creatinine_phosphokinase','ejection_fraction', 'platelets', 'serum_creatinine', 'serum_sodium')]
No_matrix <- cor(numerical_No, use = "complete.obs")
No_matrix <- round(No_matrix, 3)

par(cex.main=0.8)
lhei = c(2, 5)
heatmap.2(No_matrix, dendrogram = 'none',
          Rowv=NULL, Colv=NULL,
          trace='none', symm=TRUE,
          cexRow = 0.75, cexCol=0.75,
          key = FALSE, srtCol = 30,
          adjCol = c(0.5, 0.5),
          srtRow=50, adjRow=c(0.5,0.5),
          offsetRow = -43,
          col = colorRampPalette(c("blue", "white", "orange"))(200),
          margins = c(6.5, 5), lhei= lhei,
          cellnote = No_matrix, notecol = "black",
          )
```

**Categorical Variable EDA**

```{r, echo = TRUE, include = FALSE}
anaemia_de <- df %>% 
  group_by(anaemia, DEATH_EVENT) %>% 
  summarise(count = n()) %>% 
  mutate(prop = count / sum(count))

diabetes_de <- df %>% 
  group_by(diabetes, DEATH_EVENT) %>% 
  summarise(count = n()) %>% 
  mutate(prop = count / sum(count))

hbp_de <- df %>% 
  group_by(high_blood_pressure, DEATH_EVENT) %>% 
  summarise(count = n()) %>% 
  mutate(prop = count / sum(count))

sex_de <- df %>% 
  group_by(sex, DEATH_EVENT) %>% 
  summarise(count = n()) %>% 
  mutate(prop = count / sum(count))

smoking_de <- df %>%
  group_by(smoking, DEATH_EVENT) %>%
  summarise(count = n()) %>%
  mutate(prop = count / sum(count))
```

```{r, echo = FALSE, include = TRUE, fig.width = 10, fig.height = 8}
barchart_anaemia <- ggplot(anaemia_de, aes(x = factor(anaemia), y = prop, fill = factor(DEATH_EVENT))) +
  geom_bar(stat = "identity") +
  labs(x = "Anemia", y = "Proportion", 
       title = "Proportion of DE across Anemia") +
  theme(aspect.ratio = 0.75, plot.title = element_text(size=10),
        axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("Alive" = "royalblue", "Dead" = "red"), 
                    name = "Death Event") 

barchart_diabetes <- ggplot(diabetes_de, aes(x = factor(diabetes), y = prop, fill = factor(DEATH_EVENT))) +
  geom_bar(stat = "identity") +
  labs(x = "Diabetes", y = "Proportion", 
       title = "Proportion of DE across Diabetes") +
  theme(aspect.ratio = 0.75, plot.title = element_text(size=10),
        axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("Alive" = "seagreen3", "Dead" = "deeppink2"), 
                    name = "Death Event")

barchart_hbp <- ggplot(hbp_de, aes(x = factor(high_blood_pressure), y = prop, fill = factor(DEATH_EVENT))) +
  geom_bar(stat = "identity") +
  labs(x = "High Blood Pressure", y = "Proportion", 
       title = "Proportion of DE across HBP") +
  theme(aspect.ratio = 0.75, plot.title = element_text(size=10),
        axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("Alive" = "slateblue1", "Dead" = "brown1"), 
                    name = "Death Event")

barchart_sex <- ggplot(sex_de, aes(x = factor(sex), y = prop, fill = factor(DEATH_EVENT))) +
  geom_bar(stat = "identity") +
  labs(x = "Sex", y = "Proportion", 
       title = "Proportion of DE Across Sex") +
  theme(aspect.ratio = 0.75, plot.title = element_text(size=10),
        axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("Alive" = "dodgerblue", "Dead" = "coral"), 
                    name = "Death Event")

barchart_smoking <- ggplot(smoking_de, aes(x = factor(smoking), y = prop, fill = factor(DEATH_EVENT))) +
  geom_bar(stat = "identity") +
  labs(x = "Smoking", y = "Proportion", 
       title = "Proportion of DE Across Smoking") +
  theme(aspect.ratio = 0.75, plot.title = element_text(size=10),
        axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("Alive" = "dodgerblue", "Dead" = "coral"), 
                    name = "Death Event")

grid.arrange(barchart_anaemia, barchart_diabetes, barchart_hbp, 
             barchart_sex, barchart_smoking,
             ncol = 3)
```












